### ISSUE TITLE
Some issue with Sets

### ISSUE THREAD

**Issue by nindogo** [GitSparTV/lua-patterns#10]
I am not sure if this is an issue. I am new to Lua and love you tool.

when I do:
![image](https://github.com/GitSparTV/lua-patterns/assets/6826732/2eec9ac4-8bed-4096-92b3-98718f31320b)
I get told that
but when I do:
![image](https://github.com/GitSparTV/lua-patterns/assets/6826732/babb063d-fa3c-43d6-9336-643bcc7c44a6)
# _It says it does not match the character **{** exactly_

But I do not think it matters:
[Lua](https://tio.run/##yylN/P8/Jz85MUehJLWiRMFWQSkxBQiLq6sz0oAwJU2JS1e3oCgzr0QDpECTC8IuLgFS6Xq5iSXJGWAJHQUljei46lgtTSVNzf//AQ)
[LuaJIT](https://tio.run/##yylN1M0pTczKLPn/Pyc/OTFHoSS1okTBVkEpMQUIi6urM9KAMCVNiUtXt6AoM69EA6RAkwvCLi4BUul6uYklyRlgCR0FJY3ouOpYLU0lTc3//wE)
[OpenResty](https://tio.run/##yylN1M0vSM0rSi0uqfz/Pyc/OTFHoSS1okTBVkEpMQUIi6urM9KAMCVNiUtXt6AoM69EA6RAkwvCLi4BUul6uYklyRlgCR0FJY3ouOpYLU0lTc3//wE)

BTW - please put consider [Ethical Ads](https://www.ethicalads.io/publishers/) cos I am sure many people will be ok with you making some money from the page.

**Comment by GitSparTV** [comment]
Hi.

No, Lua pattern explanation is correct. The sign `^` negates the search.
For the string `adadas{{hfhfhdf` pattern `[^{]*` will match anything but not `{`. And the answer is correct, it found characters before `{`. If you remove `^`, it will match only `{` symbols.

Thanks for ad platform recommendation. Unfortunately, it's useless for me because I won't be able to withdraw money even if I earn them, because of restrictions to Russia.
